#ifndef OPENGL_H
#define OPENGL_H

#include <windows.h>
#include <windowsx.h>

#include "glcorearb.h"
#include "wglext.h"

void GL_Init(void);
void GL_PrintRendererInfo(void);
void GL_PrintExtensionInfo(void);

extern PFNWGLCREATECONTEXTATTRIBSARBPROC WGLCreateContextAttribsARB;
extern PFNWGLCHOOSEPIXELFORMATARBPROC    WGLChoosePixelFormatARB;
extern PFNWGLSWAPINTERVALEXTPROC         WGLSwapIntervalEXT;

// ==========
// OpenGL 1.0
// ==========

extern PFNGLCULLFACEPROC GLCullFace;
extern PFNGLFRONTFACEPROC GLFrontFace;
extern PFNGLHINTPROC GLHint;
extern PFNGLLINEWIDTHPROC GLLineWidth;
extern PFNGLPOINTSIZEPROC GLPointSize;
extern PFNGLPOLYGONMODEPROC GLPolygonMode;
extern PFNGLSCISSORPROC GLScissor;
extern PFNGLTEXPARAMETERFPROC GLTexParameterf;
extern PFNGLTEXPARAMETERFVPROC GLTexParameterfv;
extern PFNGLTEXPARAMETERIPROC GLTexParameteri;
extern PFNGLTEXPARAMETERIVPROC GLTexParameteriv;
extern PFNGLTEXIMAGE1DPROC GLTexImage1D;
extern PFNGLTEXIMAGE2DPROC GLTexImage2D;
extern PFNGLDRAWBUFFERPROC GLDrawBuffer;
extern PFNGLCLEARPROC GLClear;
extern PFNGLCLEARCOLORPROC GLClearColor;
extern PFNGLCLEARSTENCILPROC GLClearStencil;
extern PFNGLCLEARDEPTHPROC GLClearDepth;
extern PFNGLSTENCILMASKPROC GLStencilMask;
extern PFNGLCOLORMASKPROC GLColorMask;
extern PFNGLDEPTHMASKPROC GLDepthMask;
extern PFNGLDISABLEPROC GLDisable;
extern PFNGLENABLEPROC GLEnable;
extern PFNGLFINISHPROC GLFinish;
extern PFNGLFLUSHPROC GLFlush;
extern PFNGLBLENDFUNCPROC GLBlendFunc;
extern PFNGLLOGICOPPROC GLLogicOp;
extern PFNGLSTENCILFUNCPROC GLStencilFunc;
extern PFNGLSTENCILOPPROC GLStencilOp;
extern PFNGLDEPTHFUNCPROC GLDepthFunc;
extern PFNGLPIXELSTOREFPROC GLPixelStoref;
extern PFNGLPIXELSTOREIPROC GLPixelStorei;
extern PFNGLREADBUFFERPROC GLReadBuffer;
extern PFNGLREADPIXELSPROC GLReadPixels;
extern PFNGLGETBOOLEANVPROC GLGetBooleanv;
extern PFNGLGETDOUBLEVPROC GLGetDoublev;
extern PFNGLGETERRORPROC GLGetError;
extern PFNGLGETFLOATVPROC GLGetFloatv;
extern PFNGLGETINTEGERVPROC GLGetIntegerv;
extern PFNGLGETSTRINGPROC GLGetString;
extern PFNGLGETTEXIMAGEPROC GLGetTexImage;
extern PFNGLGETTEXPARAMETERFVPROC GLGetTexParameterfv;
extern PFNGLGETTEXPARAMETERIVPROC GLGetTexParameteriv;
extern PFNGLGETTEXLEVELPARAMETERFVPROC GLGetTexLevelParameterfv;
extern PFNGLGETTEXLEVELPARAMETERIVPROC GLGetTexLevelParameteriv;
extern PFNGLISENABLEDPROC GLIsEnabled;
extern PFNGLDEPTHRANGEPROC GLDepthRange;
extern PFNGLVIEWPORTPROC GLViewport;

// ==========
// OpenGL 1.1
// ==========

extern PFNGLDRAWARRAYSPROC GLDrawArrays;
extern PFNGLDRAWELEMENTSPROC GLDrawElements;
extern PFNGLGETPOINTERVPROC GLGetPointerv;
extern PFNGLPOLYGONOFFSETPROC GLPolygonOffset;
extern PFNGLCOPYTEXIMAGE1DPROC GLCopyTexImage1D;
extern PFNGLCOPYTEXIMAGE2DPROC GLCopyTexImage2D;
extern PFNGLCOPYTEXSUBIMAGE1DPROC GLCopyTexSubImage1D;
extern PFNGLCOPYTEXSUBIMAGE2DPROC GLCopyTexSubImage2D;
extern PFNGLTEXSUBIMAGE1DPROC GLTexSubImage1D;
extern PFNGLTEXSUBIMAGE2DPROC GLTexSubImage2D;
extern PFNGLBINDTEXTUREPROC GLBindTexture;
extern PFNGLDELETETEXTURESPROC GLDeleteTextures;
extern PFNGLGENTEXTURESPROC GLGenTextures;
extern PFNGLISTEXTUREPROC GLIsTexture;

// ==========
// OpenGL 1.2
// ==========

extern PFNGLDRAWRANGEELEMENTSPROC GLDrawRangeElements;
extern PFNGLTEXIMAGE3DPROC GLTexImage3D;
extern PFNGLTEXSUBIMAGE3DPROC GLTexSubImage3D;
extern PFNGLCOPYTEXSUBIMAGE3DPROC GLCopyTexSubImage3D;

// ==========
// OpenGL 1.3
// ==========

extern PFNGLACTIVETEXTUREPROC GLActiveTexture;
extern PFNGLSAMPLECOVERAGEPROC GLSampleCoverage;
extern PFNGLCOMPRESSEDTEXIMAGE3DPROC GLCompressedTexImage3D;
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC GLCompressedTexImage2D;
extern PFNGLCOMPRESSEDTEXIMAGE1DPROC GLCompressedTexImage1D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC GLCompressedTexSubImage3D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC GLCompressedTexSubImage2D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC GLCompressedTexSubImage1D;
extern PFNGLGETCOMPRESSEDTEXIMAGEPROC GLGetCompressedTexImage;

// ==========
// OpenGL 1.4
// ==========

extern PFNGLBLENDFUNCSEPARATEPROC GLBlendFuncSeparate;
extern PFNGLMULTIDRAWARRAYSPROC GLMultiDrawArrays;
extern PFNGLMULTIDRAWELEMENTSPROC GLMultiDrawElements;
extern PFNGLPOINTPARAMETERFPROC GLPointParameterf;
extern PFNGLPOINTPARAMETERFVPROC GLPointParameterfv;
extern PFNGLPOINTPARAMETERIPROC GLPointParameteri;
extern PFNGLPOINTPARAMETERIVPROC GLPointParameteriv;
extern PFNGLBLENDCOLORPROC GLBlendColor;
extern PFNGLBLENDEQUATIONPROC GLBlendEquation;

// ==========
// OpenGL 1.5
// ==========

extern PFNGLGENQUERIESPROC GLGenQueries;
extern PFNGLDELETEQUERIESPROC GLDeleteQueries;
extern PFNGLISQUERYPROC GLIsQuery;
extern PFNGLBEGINQUERYPROC GLBeginQuery;
extern PFNGLENDQUERYPROC GLEndQuery;
extern PFNGLGETQUERYIVPROC GLGetQueryiv;
extern PFNGLGETQUERYOBJECTIVPROC GLGetQueryObjectiv;
extern PFNGLGETQUERYOBJECTUIVPROC GLGetQueryObjectuiv;
extern PFNGLBINDBUFFERPROC GLBindBuffer;
extern PFNGLDELETEBUFFERSPROC GLDeleteBuffers;
extern PFNGLGENBUFFERSPROC GLGenBuffers;
extern PFNGLISBUFFERPROC GLIsBuffer;
extern PFNGLBUFFERDATAPROC GLBufferData;
extern PFNGLBUFFERSUBDATAPROC GLBufferSubData;
extern PFNGLGETBUFFERSUBDATAPROC GLGetBufferSubData;
extern PFNGLMAPBUFFERPROC GLMapBuffer;
extern PFNGLUNMAPBUFFERPROC GLUnmapBuffer;
extern PFNGLGETBUFFERPARAMETERIVPROC GLGetBufferParameteriv;
extern PFNGLGETBUFFERPOINTERVPROC GLGetBufferPointerv;

// ==========
// OpenGL 2.0
// ==========

extern PFNGLBLENDEQUATIONSEPARATEPROC GLBlendEquationSeparate;
extern PFNGLDRAWBUFFERSPROC GLDrawBuffers;
extern PFNGLSTENCILOPSEPARATEPROC GLStencilOpSeparate;
extern PFNGLSTENCILFUNCSEPARATEPROC GLStencilFuncSeparate;
extern PFNGLSTENCILMASKSEPARATEPROC GLStencilMaskSeparate;
extern PFNGLATTACHSHADERPROC GLAttachShader;
extern PFNGLBINDATTRIBLOCATIONPROC GLBindAttribLocation;
extern PFNGLCOMPILESHADERPROC GLCompileShader;
extern PFNGLCREATEPROGRAMPROC GLCreateProgram;
extern PFNGLCREATESHADERPROC GLCreateShader;
extern PFNGLDELETEPROGRAMPROC GLDeleteProgram;
extern PFNGLDELETESHADERPROC GLDeleteShader;
extern PFNGLDETACHSHADERPROC GLDetachShader;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC GLDisableVertexAttribArray;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC GLEnableVertexAttribArray;
extern PFNGLGETACTIVEATTRIBPROC GLGetActiveAttrib;
extern PFNGLGETACTIVEUNIFORMPROC GLGetActiveUniform;
extern PFNGLGETATTACHEDSHADERSPROC GLGetAttachedShaders;
extern PFNGLGETATTRIBLOCATIONPROC GLGetAttribLocation;
extern PFNGLGETPROGRAMIVPROC GLGetProgramiv;
extern PFNGLGETPROGRAMINFOLOGPROC GLGetProgramInfoLog;
extern PFNGLGETSHADERIVPROC GLGetShaderiv;
extern PFNGLGETSHADERINFOLOGPROC GLGetShaderInfoLog;
extern PFNGLGETSHADERSOURCEPROC GLGetShaderSource;
extern PFNGLGETUNIFORMLOCATIONPROC GLGetUniformLocation;
extern PFNGLGETUNIFORMFVPROC GLGetUniformfv;
extern PFNGLGETUNIFORMIVPROC GLGetUniformiv;
extern PFNGLGETVERTEXATTRIBDVPROC GLGetVertexAttribdv;
extern PFNGLGETVERTEXATTRIBFVPROC GLGetVertexAttribfv;
extern PFNGLGETVERTEXATTRIBIVPROC GLGetVertexAttribiv;
extern PFNGLGETVERTEXATTRIBPOINTERVPROC GLGetVertexAttribPointerv;
extern PFNGLISPROGRAMPROC GLIsProgram;
extern PFNGLISSHADERPROC GLIsShader;
extern PFNGLLINKPROGRAMPROC GLLinkProgram;
extern PFNGLSHADERSOURCEPROC GLShaderSource;
extern PFNGLUSEPROGRAMPROC GLUseProgram;
extern PFNGLUNIFORM1FPROC GLUniform1f;
extern PFNGLUNIFORM2FPROC GLUniform2f;
extern PFNGLUNIFORM3FPROC GLUniform3f;
extern PFNGLUNIFORM4FPROC GLUniform4f;
extern PFNGLUNIFORM1IPROC GLUniform1i;
extern PFNGLUNIFORM2IPROC GLUniform2i;
extern PFNGLUNIFORM3IPROC GLUniform3i;
extern PFNGLUNIFORM4IPROC GLUniform4i;
extern PFNGLUNIFORM1FVPROC GLUniform1fv;
extern PFNGLUNIFORM2FVPROC GLUniform2fv;
extern PFNGLUNIFORM3FVPROC GLUniform3fv;
extern PFNGLUNIFORM4FVPROC GLUniform4fv;
extern PFNGLUNIFORM1IVPROC GLUniform1iv;
extern PFNGLUNIFORM2IVPROC GLUniform2iv;
extern PFNGLUNIFORM3IVPROC GLUniform3iv;
extern PFNGLUNIFORM4IVPROC GLUniform4iv;
extern PFNGLUNIFORMMATRIX2FVPROC GLUniformMatrix2fv;
extern PFNGLUNIFORMMATRIX3FVPROC GLUniformMatrix3fv;
extern PFNGLUNIFORMMATRIX4FVPROC GLUniformMatrix4fv;
extern PFNGLVALIDATEPROGRAMPROC GLValidateProgram;
extern PFNGLVERTEXATTRIB1DPROC GLVertexAttrib1d;
extern PFNGLVERTEXATTRIB1DVPROC GLVertexAttrib1dv;
extern PFNGLVERTEXATTRIB1FPROC GLVertexAttrib1f;
extern PFNGLVERTEXATTRIB1FVPROC GLVertexAttrib1fv;
extern PFNGLVERTEXATTRIB1SPROC GLVertexAttrib1s;
extern PFNGLVERTEXATTRIB1SVPROC GLVertexAttrib1sv;
extern PFNGLVERTEXATTRIB2DPROC GLVertexAttrib2d;
extern PFNGLVERTEXATTRIB2DVPROC GLVertexAttrib2dv;
extern PFNGLVERTEXATTRIB2FPROC GLVertexAttrib2f;
extern PFNGLVERTEXATTRIB2FVPROC GLVertexAttrib2fv;
extern PFNGLVERTEXATTRIB2SPROC GLVertexAttrib2s;
extern PFNGLVERTEXATTRIB2SVPROC GLVertexAttrib2sv;
extern PFNGLVERTEXATTRIB3DPROC GLVertexAttrib3d;
extern PFNGLVERTEXATTRIB3DVPROC GLVertexAttrib3dv;
extern PFNGLVERTEXATTRIB3FPROC GLVertexAttrib3f;
extern PFNGLVERTEXATTRIB3FVPROC GLVertexAttrib3fv;
extern PFNGLVERTEXATTRIB3SPROC GLVertexAttrib3s;
extern PFNGLVERTEXATTRIB3SVPROC GLVertexAttrib3sv;
extern PFNGLVERTEXATTRIB4NBVPROC GLVertexAttrib4Nbv;
extern PFNGLVERTEXATTRIB4NIVPROC GLVertexAttrib4Niv;
extern PFNGLVERTEXATTRIB4NSVPROC GLVertexAttrib4Nsv;
extern PFNGLVERTEXATTRIB4NUBPROC GLVertexAttrib4Nub;
extern PFNGLVERTEXATTRIB4NUBVPROC GLVertexAttrib4Nubv;
extern PFNGLVERTEXATTRIB4NUIVPROC GLVertexAttrib4Nuiv;
extern PFNGLVERTEXATTRIB4NUSVPROC GLVertexAttrib4Nusv;
extern PFNGLVERTEXATTRIB4BVPROC GLVertexAttrib4bv;
extern PFNGLVERTEXATTRIB4DPROC GLVertexAttrib4d;
extern PFNGLVERTEXATTRIB4DVPROC GLVertexAttrib4dv;
extern PFNGLVERTEXATTRIB4FPROC GLVertexAttrib4f;
extern PFNGLVERTEXATTRIB4FVPROC GLVertexAttrib4fv;
extern PFNGLVERTEXATTRIB4IVPROC GLVertexAttrib4iv;
extern PFNGLVERTEXATTRIB4SPROC GLVertexAttrib4s;
extern PFNGLVERTEXATTRIB4SVPROC GLVertexAttrib4sv;
extern PFNGLVERTEXATTRIB4UBVPROC GLVertexAttrib4ubv;
extern PFNGLVERTEXATTRIB4UIVPROC GLVertexAttrib4uiv;
extern PFNGLVERTEXATTRIB4USVPROC GLVertexAttrib4usv;
extern PFNGLVERTEXATTRIBPOINTERPROC GLVertexAttribPointer;

// ==========
// OpenGL 2.1
// ==========

extern PFNGLUNIFORMMATRIX2X3FVPROC GLUniformMatrix2x3fv;
extern PFNGLUNIFORMMATRIX3X2FVPROC GLUniformMatrix3x2fv;
extern PFNGLUNIFORMMATRIX2X4FVPROC GLUniformMatrix2x4fv;
extern PFNGLUNIFORMMATRIX4X2FVPROC GLUniformMatrix4x2fv;
extern PFNGLUNIFORMMATRIX3X4FVPROC GLUniformMatrix3x4fv;
extern PFNGLUNIFORMMATRIX4X3FVPROC GLUniformMatrix4x3fv;

// ==========
// OpenGL 3.0
// ==========

extern PFNGLCOLORMASKIPROC GLColorMaski;
extern PFNGLGETBOOLEANI_VPROC GLGetBooleani_v;
extern PFNGLGETINTEGERI_VPROC GLGetIntegeri_v;
extern PFNGLENABLEIPROC GLEnablei;
extern PFNGLDISABLEIPROC GLDisablei;
extern PFNGLISENABLEDIPROC GLIsEnabledi;
extern PFNGLBEGINTRANSFORMFEEDBACKPROC GLBeginTransformFeedback;
extern PFNGLENDTRANSFORMFEEDBACKPROC GLEndTransformFeedback;
extern PFNGLBINDBUFFERRANGEPROC GLBindBufferRange;
extern PFNGLBINDBUFFERBASEPROC GLBindBufferBase;
extern PFNGLTRANSFORMFEEDBACKVARYINGSPROC GLTransformFeedbackVaryings;
extern PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GLGetTransformFeedbackVarying;
extern PFNGLCLAMPCOLORPROC GLClampColor;
extern PFNGLBEGINCONDITIONALRENDERPROC GLBeginConditionalRender;
extern PFNGLENDCONDITIONALRENDERPROC GLEndConditionalRender;
extern PFNGLVERTEXATTRIBIPOINTERPROC GLVertexAttribIPointer;
extern PFNGLGETVERTEXATTRIBIIVPROC GLGetVertexAttribIiv;
extern PFNGLGETVERTEXATTRIBIUIVPROC GLGetVertexAttribIuiv;
extern PFNGLVERTEXATTRIBI1IPROC GLVertexAttribI1i;
extern PFNGLVERTEXATTRIBI2IPROC GLVertexAttribI2i;
extern PFNGLVERTEXATTRIBI3IPROC GLVertexAttribI3i;
extern PFNGLVERTEXATTRIBI4IPROC GLVertexAttribI4i;
extern PFNGLVERTEXATTRIBI1UIPROC GLVertexAttribI1ui;
extern PFNGLVERTEXATTRIBI2UIPROC GLVertexAttribI2ui;
extern PFNGLVERTEXATTRIBI3UIPROC GLVertexAttribI3ui;
extern PFNGLVERTEXATTRIBI4UIPROC GLVertexAttribI4ui;
extern PFNGLVERTEXATTRIBI1IVPROC GLVertexAttribI1iv;
extern PFNGLVERTEXATTRIBI2IVPROC GLVertexAttribI2iv;
extern PFNGLVERTEXATTRIBI3IVPROC GLVertexAttribI3iv;
extern PFNGLVERTEXATTRIBI4IVPROC GLVertexAttribI4iv;
extern PFNGLVERTEXATTRIBI1UIVPROC GLVertexAttribI1uiv;
extern PFNGLVERTEXATTRIBI2UIVPROC GLVertexAttribI2uiv;
extern PFNGLVERTEXATTRIBI3UIVPROC GLVertexAttribI3uiv;
extern PFNGLVERTEXATTRIBI4UIVPROC GLVertexAttribI4uiv;
extern PFNGLVERTEXATTRIBI4BVPROC GLVertexAttribI4bv;
extern PFNGLVERTEXATTRIBI4SVPROC GLVertexAttribI4sv;
extern PFNGLVERTEXATTRIBI4UBVPROC GLVertexAttribI4ubv;
extern PFNGLVERTEXATTRIBI4USVPROC GLVertexAttribI4usv;
extern PFNGLGETUNIFORMUIVPROC GLGetUniformuiv;
extern PFNGLBINDFRAGDATALOCATIONPROC GLBindFragDataLocation;
extern PFNGLGETFRAGDATALOCATIONPROC GLGetFragDataLocation;
extern PFNGLUNIFORM1UIPROC GLUniform1ui;
extern PFNGLUNIFORM2UIPROC GLUniform2ui;
extern PFNGLUNIFORM3UIPROC GLUniform3ui;
extern PFNGLUNIFORM4UIPROC GLUniform4ui;
extern PFNGLUNIFORM1UIVPROC GLUniform1uiv;
extern PFNGLUNIFORM2UIVPROC GLUniform2uiv;
extern PFNGLUNIFORM3UIVPROC GLUniform3uiv;
extern PFNGLUNIFORM4UIVPROC GLUniform4uiv;
extern PFNGLTEXPARAMETERIIVPROC GLTexParameterIiv;
extern PFNGLTEXPARAMETERIUIVPROC GLTexParameterIuiv;
extern PFNGLGETTEXPARAMETERIIVPROC GLGetTexParameterIiv;
extern PFNGLGETTEXPARAMETERIUIVPROC GLGetTexParameterIuiv;
extern PFNGLCLEARBUFFERIVPROC GLClearBufferiv;
extern PFNGLCLEARBUFFERUIVPROC GLClearBufferuiv;
extern PFNGLCLEARBUFFERFVPROC GLClearBufferfv;
extern PFNGLCLEARBUFFERFIPROC GLClearBufferfi;
extern PFNGLGETSTRINGIPROC GLGetStringi;
extern PFNGLISRENDERBUFFERPROC GLIsRenderbuffer;
extern PFNGLBINDRENDERBUFFERPROC GLBindRenderbuffer;
extern PFNGLDELETERENDERBUFFERSPROC GLDeleteRenderbuffers;
extern PFNGLGENRENDERBUFFERSPROC GLGenRenderbuffers;
extern PFNGLRENDERBUFFERSTORAGEPROC GLRenderbufferStorage;
extern PFNGLGETRENDERBUFFERPARAMETERIVPROC GLGetRenderbufferParameteriv;
extern PFNGLISFRAMEBUFFERPROC GLIsFramebuffer;
extern PFNGLBINDFRAMEBUFFERPROC GLBindFramebuffer;
extern PFNGLDELETEFRAMEBUFFERSPROC GLDeleteFramebuffers;
extern PFNGLGENFRAMEBUFFERSPROC GLGenFramebuffers;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC GLCheckFramebufferStatus;
extern PFNGLFRAMEBUFFERTEXTURE1DPROC GLFramebufferTexture1D;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC GLFramebufferTexture2D;
extern PFNGLFRAMEBUFFERTEXTURE3DPROC GLFramebufferTexture3D;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC GLFramebufferRenderbuffer;
extern PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GLGetFramebufferAttachmentParameteriv;
extern PFNGLGENERATEMIPMAPPROC GLGenerateMipmap;
extern PFNGLBLITFRAMEBUFFERPROC GLBlitFramebuffer;
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC GLRenderbufferStorageMultisample;
extern PFNGLFRAMEBUFFERTEXTURELAYERPROC GLFramebufferTextureLayer;
extern PFNGLMAPBUFFERRANGEPROC GLMapBufferRange;
extern PFNGLFLUSHMAPPEDBUFFERRANGEPROC GLFlushMappedBufferRange;
extern PFNGLBINDVERTEXARRAYPROC GLBindVertexArray;
extern PFNGLDELETEVERTEXARRAYSPROC GLDeleteVertexArrays;
extern PFNGLGENVERTEXARRAYSPROC GLGenVertexArrays;
extern PFNGLISVERTEXARRAYPROC GLIsVertexArray;

#endif
