#include "OpenGL.h"
#include "System.h"
#include <stdio.h>

// WGL Extensions
PFNWGLCREATECONTEXTATTRIBSARBPROC WGLCreateContextAttribsARB;
PFNWGLCHOOSEPIXELFORMATARBPROC    WGLChoosePixelFormatARB;
PFNWGLSWAPINTERVALEXTPROC         WGLSwapIntervalEXT;

// OpenGL 1.0

PFNGLCULLFACEPROC GLCullFace;
PFNGLFRONTFACEPROC GLFrontFace;
PFNGLHINTPROC GLHint;
PFNGLLINEWIDTHPROC GLLineWidth;
PFNGLPOINTSIZEPROC GLPointSize;
PFNGLPOLYGONMODEPROC GLPolygonMode;
PFNGLSCISSORPROC GLScissor;
PFNGLTEXPARAMETERFPROC GLTexParameterf;
PFNGLTEXPARAMETERFVPROC GLTexParameterfv;
PFNGLTEXPARAMETERIPROC GLTexParameteri;
PFNGLTEXPARAMETERIVPROC GLTexParameteriv;
PFNGLTEXIMAGE1DPROC GLTexImage1D;
PFNGLTEXIMAGE2DPROC GLTexImage2D;
PFNGLDRAWBUFFERPROC GLDrawBuffer;
PFNGLCLEARPROC GLClear;
PFNGLCLEARCOLORPROC GLClearColor;
PFNGLCLEARSTENCILPROC GLClearStencil;
PFNGLCLEARDEPTHPROC GLClearDepth;
PFNGLSTENCILMASKPROC GLStencilMask;
PFNGLCOLORMASKPROC GLColorMask;
PFNGLDEPTHMASKPROC GLDepthMask;
PFNGLDISABLEPROC GLDisable;
PFNGLENABLEPROC GLEnable;
PFNGLFINISHPROC GLFinish;
PFNGLFLUSHPROC GLFlush;
PFNGLBLENDFUNCPROC GLBlendFunc;
PFNGLLOGICOPPROC GLLogicOp;
PFNGLSTENCILFUNCPROC GLStencilFunc;
PFNGLSTENCILOPPROC GLStencilOp;
PFNGLDEPTHFUNCPROC GLDepthFunc;
PFNGLPIXELSTOREFPROC GLPixelStoref;
PFNGLPIXELSTOREIPROC GLPixelStorei;
PFNGLREADBUFFERPROC GLReadBuffer;
PFNGLREADPIXELSPROC GLReadPixels;
PFNGLGETBOOLEANVPROC GLGetBooleanv;
PFNGLGETDOUBLEVPROC GLGetDoublev;
PFNGLGETERRORPROC GLGetError;
PFNGLGETFLOATVPROC GLGetFloatv;
PFNGLGETINTEGERVPROC GLGetIntegerv;
PFNGLPIENTRY proc GLPIENTRY ;
PFNGLGETTEXIMAGEPROC GLGetTexImage;
PFNGLGETTEXPARAMETERFVPROC GLGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC GLGetTexParameteriv;
PFNGLGETTEXLEVELPARAMETERFVPROC GLGetTexLevelParameterfv;
PFNGLGETTEXLEVELPARAMETERIVPROC GLGetTexLevelParameteriv;
PFNGLISENABLEDPROC GLIsEnabled;
PFNGLDEPTHRANGEPROC GLDepthRange;
PFNGLVIEWPORTPROC GLViewport;
PFNGLDRAWARRAYSPROC GLDrawArrays;
PFNGLDRAWELEMENTSPROC GLDrawElements;
PFNGLGETPOINTERVPROC GLGetPointerv;
PFNGLPOLYGONOFFSETPROC GLPolygonOffset;
PFNGLCOPYTEXIMAGE1DPROC GLCopyTexImage1D;
PFNGLCOPYTEXIMAGE2DPROC GLCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE1DPROC GLCopyTexSubImage1D;
PFNGLCOPYTEXSUBIMAGE2DPROC GLCopyTexSubImage2D;
PFNGLTEXSUBIMAGE1DPROC GLTexSubImage1D;
PFNGLTEXSUBIMAGE2DPROC GLTexSubImage2D;
PFNGLBINDTEXTUREPROC GLBindTexture;
PFNGLDELETETEXTURESPROC GLDeleteTextures;
PFNGLGENTEXTURESPROC GLGenTextures;
PFNGLISTEXTUREPROC GLIsTexture;
PFNGLDRAWRANGEELEMENTSPROC GLDrawRangeElements;
PFNGLTEXIMAGE3DPROC GLTexImage3D;
PFNGLTEXSUBIMAGE3DPROC GLTexSubImage3D;
PFNGLCOPYTEXSUBIMAGE3DPROC GLCopyTexSubImage3D;
PFNGLACTIVETEXTUREPROC GLActiveTexture;
PFNGLSAMPLECOVERAGEPROC GLSampleCoverage;
PFNGLCOMPRESSEDTEXIMAGE3DPROC GLCompressedTexImage3D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC GLCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE1DPROC GLCompressedTexImage1D;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC GLCompressedTexSubImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC GLCompressedTexSubImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC GLCompressedTexSubImage1D;
PFNGLGETCOMPRESSEDTEXIMAGEPROC GLGetCompressedTexImage;
PFNGLBLENDFUNCSEPARATEPROC GLBlendFuncSeparate;
PFNGLMULTIDRAWARRAYSPROC GLMultiDrawArrays;
PFNGLMULTIDRAWELEMENTSPROC GLMultiDrawElements;
PFNGLPOINTPARAMETERFPROC GLPointParameterf;
PFNGLPOINTPARAMETERFVPROC GLPointParameterfv;
PFNGLPOINTPARAMETERIPROC GLPointParameteri;
PFNGLPOINTPARAMETERIVPROC GLPointParameteriv;
PFNGLBLENDCOLORPROC GLBlendColor;
PFNGLBLENDEQUATIONPROC GLBlendEquation;
PFNGLGENQUERIESPROC GLGenQueries;
PFNGLDELETEQUERIESPROC GLDeleteQueries;
PFNGLISQUERYPROC GLIsQuery;
PFNGLBEGINQUERYPROC GLBeginQuery;
PFNGLENDQUERYPROC GLEndQuery;
PFNGLGETQUERYIVPROC GLGetQueryiv;
PFNGLGETQUERYOBJECTIVPROC GLGetQueryObjectiv;
PFNGLGETQUERYOBJECTUIVPROC GLGetQueryObjectuiv;
PFNGLBINDBUFFERPROC GLBindBuffer;
PFNGLDELETEBUFFERSPROC GLDeleteBuffers;
PFNGLGENBUFFERSPROC GLGenBuffers;
PFNGLISBUFFERPROC GLIsBuffer;
PFNGLBUFFERDATAPROC GLBufferData;
PFNGLBUFFERSUBDATAPROC GLBufferSubData;
PFNGLGETBUFFERSUBDATAPROC GLGetBufferSubData;
PFNGLMAPBUFFERPROC GLMapBuffer;
PFNGLUNMAPBUFFERPROC GLUnmapBuffer;
PFNGLGETBUFFERPARAMETERIVPROC GLGetBufferParameteriv;
PFNGLGETBUFFERPOINTERVPROC GLGetBufferPointerv;
PFNGLBLENDEQUATIONSEPARATEPROC GLBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC GLDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC GLStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC GLStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC GLStencilMaskSeparate;
PFNGLATTACHSHADERPROC GLAttachShader;
PFNGLBINDATTRIBLOCATIONPROC GLBindAttribLocation;
PFNGLCOMPILESHADERPROC GLCompileShader;
PFNGLCREATEPROGRAMPROC GLCreateProgram;
PFNGLCREATESHADERPROC GLCreateShader;
PFNGLDELETEPROGRAMPROC GLDeleteProgram;
PFNGLDELETESHADERPROC GLDeleteShader;
PFNGLDETACHSHADERPROC GLDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC GLDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC GLEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC GLGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC GLGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC GLGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC GLGetAttribLocation;
PFNGLGETPROGRAMIVPROC GLGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC GLGetProgramInfoLog;
PFNGLGETSHADERIVPROC GLGetShaderiv;
PFNGLGETSHADERINFOLOGPROC GLGetShaderInfoLog;
PFNGLGETSHADERSOURCEPROC GLGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC GLGetUniformLocation;
PFNGLGETUNIFORMFVPROC GLGetUniformfv;
PFNGLGETUNIFORMIVPROC GLGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC GLGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC GLGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC GLGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC GLGetVertexAttribPointerv;
PFNGLISPROGRAMPROC GLIsProgram;
PFNGLISSHADERPROC GLIsShader;
PFNGLLINKPROGRAMPROC GLLinkProgram;
PFNGLSHADERSOURCEPROC GLShaderSource;
PFNGLUSEPROGRAMPROC GLUseProgram;
PFNGLUNIFORM1FPROC GLUniform1f;
PFNGLUNIFORM2FPROC GLUniform2f;
PFNGLUNIFORM3FPROC GLUniform3f;
PFNGLUNIFORM4FPROC GLUniform4f;
PFNGLUNIFORM1IPROC GLUniform1i;
PFNGLUNIFORM2IPROC GLUniform2i;
PFNGLUNIFORM3IPROC GLUniform3i;
PFNGLUNIFORM4IPROC GLUniform4i;
PFNGLUNIFORM1FVPROC GLUniform1fv;
PFNGLUNIFORM2FVPROC GLUniform2fv;
PFNGLUNIFORM3FVPROC GLUniform3fv;
PFNGLUNIFORM4FVPROC GLUniform4fv;
PFNGLUNIFORM1IVPROC GLUniform1iv;
PFNGLUNIFORM2IVPROC GLUniform2iv;
PFNGLUNIFORM3IVPROC GLUniform3iv;
PFNGLUNIFORM4IVPROC GLUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC GLUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC GLUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC GLUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC GLValidateProgram;
PFNGLVERTEXATTRIB1DPROC GLVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC GLVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC GLVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC GLVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC GLVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC GLVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC GLVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC GLVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC GLVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC GLVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC GLVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC GLVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC GLVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC GLVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC GLVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC GLVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC GLVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC GLVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC GLVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC GLVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC GLVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC GLVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC GLVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC GLVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC GLVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC GLVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC GLVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC GLVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC GLVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC GLVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC GLVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC GLVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC GLVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC GLVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC GLVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC GLVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC GLVertexAttribPointer;
PFNGLUNIFORMMATRIX2X3FVPROC GLUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC GLUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC GLUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC GLUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC GLUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC GLUniformMatrix4x3fv;
PFNGLCOLORMASKIPROC GLColorMaski;
PFNGLGETBOOLEANI_VPROC GLGetBooleani_v;
PFNGLGETINTEGERI_VPROC GLGetIntegeri_v;
PFNGLENABLEIPROC GLEnablei;
PFNGLDISABLEIPROC GLDisablei;
PFNGLISENABLEDIPROC GLIsEnabledi;
PFNGLBEGINTRANSFORMFEEDBACKPROC GLBeginTransformFeedback;
PFNGLENDTRANSFORMFEEDBACKPROC GLEndTransformFeedback;
PFNGLBINDBUFFERRANGEPROC GLBindBufferRange;
PFNGLBINDBUFFERBASEPROC GLBindBufferBase;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC GLTransformFeedbackVaryings;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GLGetTransformFeedbackVarying;
PFNGLCLAMPCOLORPROC GLClampColor;
PFNGLBEGINCONDITIONALRENDERPROC GLBeginConditionalRender;
PFNGLENDCONDITIONALRENDERPROC GLEndConditionalRender;
PFNGLVERTEXATTRIBIPOINTERPROC GLVertexAttribIPointer;
PFNGLGETVERTEXATTRIBIIVPROC GLGetVertexAttribIiv;
PFNGLGETVERTEXATTRIBIUIVPROC GLGetVertexAttribIuiv;
PFNGLVERTEXATTRIBI1IPROC GLVertexAttribI1i;
PFNGLVERTEXATTRIBI2IPROC GLVertexAttribI2i;
PFNGLVERTEXATTRIBI3IPROC GLVertexAttribI3i;
PFNGLVERTEXATTRIBI4IPROC GLVertexAttribI4i;
PFNGLVERTEXATTRIBI1UIPROC GLVertexAttribI1ui;
PFNGLVERTEXATTRIBI2UIPROC GLVertexAttribI2ui;
PFNGLVERTEXATTRIBI3UIPROC GLVertexAttribI3ui;
PFNGLVERTEXATTRIBI4UIPROC GLVertexAttribI4ui;
PFNGLVERTEXATTRIBI1IVPROC GLVertexAttribI1iv;
PFNGLVERTEXATTRIBI2IVPROC GLVertexAttribI2iv;
PFNGLVERTEXATTRIBI3IVPROC GLVertexAttribI3iv;
PFNGLVERTEXATTRIBI4IVPROC GLVertexAttribI4iv;
PFNGLVERTEXATTRIBI1UIVPROC GLVertexAttribI1uiv;
PFNGLVERTEXATTRIBI2UIVPROC GLVertexAttribI2uiv;
PFNGLVERTEXATTRIBI3UIVPROC GLVertexAttribI3uiv;
PFNGLVERTEXATTRIBI4UIVPROC GLVertexAttribI4uiv;
PFNGLVERTEXATTRIBI4BVPROC GLVertexAttribI4bv;
PFNGLVERTEXATTRIBI4SVPROC GLVertexAttribI4sv;
PFNGLVERTEXATTRIBI4UBVPROC GLVertexAttribI4ubv;
PFNGLVERTEXATTRIBI4USVPROC GLVertexAttribI4usv;
PFNGLGETUNIFORMUIVPROC GLGetUniformuiv;
PFNGLBINDFRAGDATALOCATIONPROC GLBindFragDataLocation;
PFNGLGETFRAGDATALOCATIONPROC GLGetFragDataLocation;
PFNGLUNIFORM1UIPROC GLUniform1ui;
PFNGLUNIFORM2UIPROC GLUniform2ui;
PFNGLUNIFORM3UIPROC GLUniform3ui;
PFNGLUNIFORM4UIPROC GLUniform4ui;
PFNGLUNIFORM1UIVPROC GLUniform1uiv;
PFNGLUNIFORM2UIVPROC GLUniform2uiv;
PFNGLUNIFORM3UIVPROC GLUniform3uiv;
PFNGLUNIFORM4UIVPROC GLUniform4uiv;
PFNGLTEXPARAMETERIIVPROC GLTexParameterIiv;
PFNGLTEXPARAMETERIUIVPROC GLTexParameterIuiv;
PFNGLGETTEXPARAMETERIIVPROC GLGetTexParameterIiv;
PFNGLGETTEXPARAMETERIUIVPROC GLGetTexParameterIuiv;
PFNGLCLEARBUFFERIVPROC GLClearBufferiv;
PFNGLCLEARBUFFERUIVPROC GLClearBufferuiv;
PFNGLCLEARBUFFERFVPROC GLClearBufferfv;
PFNGLCLEARBUFFERFIPROC GLClearBufferfi;
PFNGLPIENTRY proc GLPIENTRY ;
PFNGLISRENDERBUFFERPROC GLIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC GLBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC GLDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC GLGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC GLRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC GLGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC GLIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC GLBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC GLDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC GLGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC GLCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC GLFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC GLFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC GLFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC GLFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GLGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC GLGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC GLBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC GLRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC GLFramebufferTextureLayer;
PFNGLMAPBUFFERRANGEPROC GLMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC GLFlushMappedBufferRange;
PFNGLBINDVERTEXARRAYPROC GLBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC GLDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC GLGenVertexArrays;
PFNGLISVERTEXARRAYPROC GLIsVertexArray;

void
GL_PrintRendererInfo(void)
{
    printf(
        "OpenGL Renderer: %s\n",
        (const char*)GLGetString(GL_RENDERER));

    printf(
        "OpenGL Vendor:   %s\n",
        (const char*)GLGetString(GL_VENDOR));

    printf(
        "OpenGL Version:  %s\n",
        (const char*)GLGetString(GL_VERSION));

    printf(
        "GLSL Version:    %s\n",
        (const char*)GLGetString(GL_SHADING_LANGUAGE_VERSION));

    printf("\n");
}

void
GL_PrintExtensionInfo(void)
{
    int numExtensions;
    glGetIntegerv(GL_NUM_EXTENSIONS, &numExtensions);

    printf("There are %d OpenGL extensions available\n", numExtensions);
    printf("\n");

    for(int i = 0; i < numExtensions; i++)
    {
        const char* extName = (const char*)GLGetStringi(GL_EXTENSIONS, i);
        printf("%s\n", extName);
    }

    printf("\n");
}

void
GL_Init(void)
{
    Sys_LoadGLProc((void**)&WGLCreateContextAttribsARB, 0, 0, "wglCreateContextAttribsARB");
    Sys_LoadGLProc((void**)&WGLChoosePixelFormatARB,    0, 0, "wglChoosePixelFormatARB");
    Sys_LoadGLProc((void**)&WGLSwapIntervalEXT,         0, 0, "wglSwapIntervalEXT");

    // OpenGL 1.0
    Sys_LoadGLProc((void**)&GLClear,       1, 0, "glClear");
    Sys_LoadGLProc((void**)&GLClearColor,  1, 0, "glClearColor");
    Sys_LoadGLProc((void**)&GLGetString,   1, 0, "glGetString");
    Sys_LoadGLProc((void**)&GLGetIntegerv, 1, 0, "glGetIntegerv");

    // OpenGL 2.0 [Program]
    Sys_LoadGLProc((void**)&GLCreateProgram,     2, 0, "glCreateProgram");
    Sys_LoadGLProc((void**)&GLAttachShader,      2, 0, "glAttachShader");
    Sys_LoadGLProc((void**)&GLLinkProgram,       2, 0, "glLinkProgram");
    Sys_LoadGLProc((void**)&GLGetProgramiv,      2, 0, "glGetProgramiv");
    Sys_LoadGLProc((void**)&GLGetProgramInfoLog, 2, 0, "glGetProgramInfoLog");

    // OpenGL 2.0 [Shader]
    Sys_LoadGLProc((void**)&GLCreateShader,     2, 0, "glCreateShader");
    Sys_LoadGLProc((void**)&GLShaderSource,     2, 0, "glShaderSource");
    Sys_LoadGLProc((void**)&GLCompileShader,    2, 0, "glCompileShader");
    Sys_LoadGLProc((void**)&GLGetShaderiv,      2, 0, "glGetShaderiv");
    Sys_LoadGLProc((void**)&GLGetShaderInfoLog, 2, 0, "glGetShaderInfoLog");

    // OpenGL 3.0
    Sys_LoadGLProc((void**)&GLGetStringi, 3, 0, "glGetStringi");
    
    // 

    Sys_LoadGLProc((void**)&GLCullFace, "glCullFace");
    Sys_LoadGLProc((void**)&GLFrontFace, "glFrontFace");
    Sys_LoadGLProc((void**)&GLHint, "glHint");
    Sys_LoadGLProc((void**)&GLLineWidth, "glLineWidth");
    Sys_LoadGLProc((void**)&GLPointSize, "glPointSize");
    Sys_LoadGLProc((void**)&GLPolygonMode, "glPolygonMode");
    Sys_LoadGLProc((void**)&GLScissor, "glScissor");
    Sys_LoadGLProc((void**)&GLTexParameterf, "glTexParameterf");
    Sys_LoadGLProc((void**)&GLTexParameterfv, "glTexParameterfv");
    Sys_LoadGLProc((void**)&GLTexParameteri, "glTexParameteri");
    Sys_LoadGLProc((void**)&GLTexParameteriv, "glTexParameteriv");
    Sys_LoadGLProc((void**)&GLTexImage1D, "glTexImage1D");
    Sys_LoadGLProc((void**)&GLTexImage2D, "glTexImage2D");
    Sys_LoadGLProc((void**)&GLDrawBuffer, "glDrawBuffer");
    Sys_LoadGLProc((void**)&GLClear, "glClear");
    Sys_LoadGLProc((void**)&GLClearColor, "glClearColor");
    Sys_LoadGLProc((void**)&GLClearStencil, "glClearStencil");
    Sys_LoadGLProc((void**)&GLClearDepth, "glClearDepth");
    Sys_LoadGLProc((void**)&GLStencilMask, "glStencilMask");
    Sys_LoadGLProc((void**)&GLColorMask, "glColorMask");
    Sys_LoadGLProc((void**)&GLDepthMask, "glDepthMask");
    Sys_LoadGLProc((void**)&GLDisable, "glDisable");
    Sys_LoadGLProc((void**)&GLEnable, "glEnable");
    Sys_LoadGLProc((void**)&GLFinish, "glFinish");
    Sys_LoadGLProc((void**)&GLFlush, "glFlush");
    Sys_LoadGLProc((void**)&GLBlendFunc, "glBlendFunc");
    Sys_LoadGLProc((void**)&GLLogicOp, "glLogicOp");
    Sys_LoadGLProc((void**)&GLStencilFunc, "glStencilFunc");
    Sys_LoadGLProc((void**)&GLStencilOp, "glStencilOp");
    Sys_LoadGLProc((void**)&GLDepthFunc, "glDepthFunc");
    Sys_LoadGLProc((void**)&GLPixelStoref, "glPixelStoref");
    Sys_LoadGLProc((void**)&GLPixelStorei, "glPixelStorei");
    Sys_LoadGLProc((void**)&GLReadBuffer, "glReadBuffer");
    Sys_LoadGLProc((void**)&GLReadPixels, "glReadPixels");
    Sys_LoadGLProc((void**)&GLGetBooleanv, "glGetBooleanv");
    Sys_LoadGLProc((void**)&GLGetDoublev, "glGetDoublev");
    Sys_LoadGLProc((void**)&GLGetError, "glGetError");
    Sys_LoadGLProc((void**)&GLGetFloatv, "glGetFloatv");
    Sys_LoadGLProc((void**)&GLGetIntegerv, "glGetIntegerv");
    Sys_LoadGLProc((void**)&proc GLPIENTRY , "gloc ");
    Sys_LoadGLProc((void**)&GLGetTexImage, "glGetTexImage");
    Sys_LoadGLProc((void**)&GLGetTexParameterfv, "glGetTexParameterfv");
    Sys_LoadGLProc((void**)&GLGetTexParameteriv, "glGetTexParameteriv");
    Sys_LoadGLProc((void**)&GLGetTexLevelParameterfv, "glGetTexLevelParameterfv");
    Sys_LoadGLProc((void**)&GLGetTexLevelParameteriv, "glGetTexLevelParameteriv");
    Sys_LoadGLProc((void**)&GLIsEnabled, "glIsEnabled");
    Sys_LoadGLProc((void**)&GLDepthRange, "glDepthRange");
    Sys_LoadGLProc((void**)&GLViewport, "glViewport");
    Sys_LoadGLProc((void**)&GLDrawArrays, "glDrawArrays");
    Sys_LoadGLProc((void**)&GLDrawElements, "glDrawElements");
    Sys_LoadGLProc((void**)&GLGetPointerv, "glGetPointerv");
    Sys_LoadGLProc((void**)&GLPolygonOffset, "glPolygonOffset");
    Sys_LoadGLProc((void**)&GLCopyTexImage1D, "glCopyTexImage1D");
    Sys_LoadGLProc((void**)&GLCopyTexImage2D, "glCopyTexImage2D");
    Sys_LoadGLProc((void**)&GLCopyTexSubImage1D, "glCopyTexSubImage1D");
    Sys_LoadGLProc((void**)&GLCopyTexSubImage2D, "glCopyTexSubImage2D");
    Sys_LoadGLProc((void**)&GLTexSubImage1D, "glTexSubImage1D");
    Sys_LoadGLProc((void**)&GLTexSubImage2D, "glTexSubImage2D");
    Sys_LoadGLProc((void**)&GLBindTexture, "glBindTexture");
    Sys_LoadGLProc((void**)&GLDeleteTextures, "glDeleteTextures");
    Sys_LoadGLProc((void**)&GLGenTextures, "glGenTextures");
    Sys_LoadGLProc((void**)&GLIsTexture, "glIsTexture");
    Sys_LoadGLProc((void**)&GLDrawRangeElements, "glDrawRangeElements");
    Sys_LoadGLProc((void**)&GLTexImage3D, "glTexImage3D");
    Sys_LoadGLProc((void**)&GLTexSubImage3D, "glTexSubImage3D");
    Sys_LoadGLProc((void**)&GLCopyTexSubImage3D, "glCopyTexSubImage3D");
    Sys_LoadGLProc((void**)&GLActiveTexture, "glActiveTexture");
    Sys_LoadGLProc((void**)&GLSampleCoverage, "glSampleCoverage");
    Sys_LoadGLProc((void**)&GLCompressedTexImage3D, "glCompressedTexImage3D");
    Sys_LoadGLProc((void**)&GLCompressedTexImage2D, "glCompressedTexImage2D");
    Sys_LoadGLProc((void**)&GLCompressedTexImage1D, "glCompressedTexImage1D");
    Sys_LoadGLProc((void**)&GLCompressedTexSubImage3D, "glCompressedTexSubImage3D");
    Sys_LoadGLProc((void**)&GLCompressedTexSubImage2D, "glCompressedTexSubImage2D");
    Sys_LoadGLProc((void**)&GLCompressedTexSubImage1D, "glCompressedTexSubImage1D");
    Sys_LoadGLProc((void**)&GLGetCompressedTexImage, "glGetCompressedTexImage");
    Sys_LoadGLProc((void**)&GLBlendFuncSeparate, "glBlendFuncSeparate");
    Sys_LoadGLProc((void**)&GLMultiDrawArrays, "glMultiDrawArrays");
    Sys_LoadGLProc((void**)&GLMultiDrawElements, "glMultiDrawElements");
    Sys_LoadGLProc((void**)&GLPointParameterf, "glPointParameterf");
    Sys_LoadGLProc((void**)&GLPointParameterfv, "glPointParameterfv");
    Sys_LoadGLProc((void**)&GLPointParameteri, "glPointParameteri");
    Sys_LoadGLProc((void**)&GLPointParameteriv, "glPointParameteriv");
    Sys_LoadGLProc((void**)&GLBlendColor, "glBlendColor");
    Sys_LoadGLProc((void**)&GLBlendEquation, "glBlendEquation");
    Sys_LoadGLProc((void**)&GLGenQueries, "glGenQueries");
    Sys_LoadGLProc((void**)&GLDeleteQueries, "glDeleteQueries");
    Sys_LoadGLProc((void**)&GLIsQuery, "glIsQuery");
    Sys_LoadGLProc((void**)&GLBeginQuery, "glBeginQuery");
    Sys_LoadGLProc((void**)&GLEndQuery, "glEndQuery");
    Sys_LoadGLProc((void**)&GLGetQueryiv, "glGetQueryiv");
    Sys_LoadGLProc((void**)&GLGetQueryObjectiv, "glGetQueryObjectiv");
    Sys_LoadGLProc((void**)&GLGetQueryObjectuiv, "glGetQueryObjectuiv");
    Sys_LoadGLProc((void**)&GLBindBuffer, "glBindBuffer");
    Sys_LoadGLProc((void**)&GLDeleteBuffers, "glDeleteBuffers");
    Sys_LoadGLProc((void**)&GLGenBuffers, "glGenBuffers");
    Sys_LoadGLProc((void**)&GLIsBuffer, "glIsBuffer");
    Sys_LoadGLProc((void**)&GLBufferData, "glBufferData");
    Sys_LoadGLProc((void**)&GLBufferSubData, "glBufferSubData");
    Sys_LoadGLProc((void**)&GLGetBufferSubData, "glGetBufferSubData");
    Sys_LoadGLProc((void**)&GLMapBuffer, "glMapBuffer");
    Sys_LoadGLProc((void**)&GLUnmapBuffer, "glUnmapBuffer");
    Sys_LoadGLProc((void**)&GLGetBufferParameteriv, "glGetBufferParameteriv");
    Sys_LoadGLProc((void**)&GLGetBufferPointerv, "glGetBufferPointerv");
    Sys_LoadGLProc((void**)&GLBlendEquationSeparate, "glBlendEquationSeparate");
    Sys_LoadGLProc((void**)&GLDrawBuffers, "glDrawBuffers");
    Sys_LoadGLProc((void**)&GLStencilOpSeparate, "glStencilOpSeparate");
    Sys_LoadGLProc((void**)&GLStencilFuncSeparate, "glStencilFuncSeparate");
    Sys_LoadGLProc((void**)&GLStencilMaskSeparate, "glStencilMaskSeparate");
    Sys_LoadGLProc((void**)&GLAttachShader, "glAttachShader");
    Sys_LoadGLProc((void**)&GLBindAttribLocation, "glBindAttribLocation");
    Sys_LoadGLProc((void**)&GLCompileShader, "glCompileShader");
    Sys_LoadGLProc((void**)&GLCreateProgram, "glCreateProgram");
    Sys_LoadGLProc((void**)&GLCreateShader, "glCreateShader");
    Sys_LoadGLProc((void**)&GLDeleteProgram, "glDeleteProgram");
    Sys_LoadGLProc((void**)&GLDeleteShader, "glDeleteShader");
    Sys_LoadGLProc((void**)&GLDetachShader, "glDetachShader");
    Sys_LoadGLProc((void**)&GLDisableVertexAttribArray, "glDisableVertexAttribArray");
    Sys_LoadGLProc((void**)&GLEnableVertexAttribArray, "glEnableVertexAttribArray");
    Sys_LoadGLProc((void**)&GLGetActiveAttrib, "glGetActiveAttrib");
    Sys_LoadGLProc((void**)&GLGetActiveUniform, "glGetActiveUniform");
    Sys_LoadGLProc((void**)&GLGetAttachedShaders, "glGetAttachedShaders");
    Sys_LoadGLProc((void**)&GLGetAttribLocation, "glGetAttribLocation");
    Sys_LoadGLProc((void**)&GLGetProgramiv, "glGetProgramiv");
    Sys_LoadGLProc((void**)&GLGetProgramInfoLog, "glGetProgramInfoLog");
    Sys_LoadGLProc((void**)&GLGetShaderiv, "glGetShaderiv");
    Sys_LoadGLProc((void**)&GLGetShaderInfoLog, "glGetShaderInfoLog");
    Sys_LoadGLProc((void**)&GLGetShaderSource, "glGetShaderSource");
    Sys_LoadGLProc((void**)&GLGetUniformLocation, "glGetUniformLocation");
    Sys_LoadGLProc((void**)&GLGetUniformfv, "glGetUniformfv");
    Sys_LoadGLProc((void**)&GLGetUniformiv, "glGetUniformiv");
    Sys_LoadGLProc((void**)&GLGetVertexAttribdv, "glGetVertexAttribdv");
    Sys_LoadGLProc((void**)&GLGetVertexAttribfv, "glGetVertexAttribfv");
    Sys_LoadGLProc((void**)&GLGetVertexAttribiv, "glGetVertexAttribiv");
    Sys_LoadGLProc((void**)&GLGetVertexAttribPointerv, "glGetVertexAttribPointerv");
    Sys_LoadGLProc((void**)&GLIsProgram, "glIsProgram");
    Sys_LoadGLProc((void**)&GLIsShader, "glIsShader");
    Sys_LoadGLProc((void**)&GLLinkProgram, "glLinkProgram");
    Sys_LoadGLProc((void**)&GLShaderSource, "glShaderSource");
    Sys_LoadGLProc((void**)&GLUseProgram, "glUseProgram");
    Sys_LoadGLProc((void**)&GLUniform1f, "glUniform1f");
    Sys_LoadGLProc((void**)&GLUniform2f, "glUniform2f");
    Sys_LoadGLProc((void**)&GLUniform3f, "glUniform3f");
    Sys_LoadGLProc((void**)&GLUniform4f, "glUniform4f");
    Sys_LoadGLProc((void**)&GLUniform1i, "glUniform1i");
    Sys_LoadGLProc((void**)&GLUniform2i, "glUniform2i");
    Sys_LoadGLProc((void**)&GLUniform3i, "glUniform3i");
    Sys_LoadGLProc((void**)&GLUniform4i, "glUniform4i");
    Sys_LoadGLProc((void**)&GLUniform1fv, "glUniform1fv");
    Sys_LoadGLProc((void**)&GLUniform2fv, "glUniform2fv");
    Sys_LoadGLProc((void**)&GLUniform3fv, "glUniform3fv");
    Sys_LoadGLProc((void**)&GLUniform4fv, "glUniform4fv");
    Sys_LoadGLProc((void**)&GLUniform1iv, "glUniform1iv");
    Sys_LoadGLProc((void**)&GLUniform2iv, "glUniform2iv");
    Sys_LoadGLProc((void**)&GLUniform3iv, "glUniform3iv");
    Sys_LoadGLProc((void**)&GLUniform4iv, "glUniform4iv");
    Sys_LoadGLProc((void**)&GLUniformMatrix2fv, "glUniformMatrix2fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix3fv, "glUniformMatrix3fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix4fv, "glUniformMatrix4fv");
    Sys_LoadGLProc((void**)&GLValidateProgram, "glValidateProgram");
    Sys_LoadGLProc((void**)&GLVertexAttrib1d, "glVertexAttrib1d");
    Sys_LoadGLProc((void**)&GLVertexAttrib1dv, "glVertexAttrib1dv");
    Sys_LoadGLProc((void**)&GLVertexAttrib1f, "glVertexAttrib1f");
    Sys_LoadGLProc((void**)&GLVertexAttrib1fv, "glVertexAttrib1fv");
    Sys_LoadGLProc((void**)&GLVertexAttrib1s, "glVertexAttrib1s");
    Sys_LoadGLProc((void**)&GLVertexAttrib1sv, "glVertexAttrib1sv");
    Sys_LoadGLProc((void**)&GLVertexAttrib2d, "glVertexAttrib2d");
    Sys_LoadGLProc((void**)&GLVertexAttrib2dv, "glVertexAttrib2dv");
    Sys_LoadGLProc((void**)&GLVertexAttrib2f, "glVertexAttrib2f");
    Sys_LoadGLProc((void**)&GLVertexAttrib2fv, "glVertexAttrib2fv");
    Sys_LoadGLProc((void**)&GLVertexAttrib2s, "glVertexAttrib2s");
    Sys_LoadGLProc((void**)&GLVertexAttrib2sv, "glVertexAttrib2sv");
    Sys_LoadGLProc((void**)&GLVertexAttrib3d, "glVertexAttrib3d");
    Sys_LoadGLProc((void**)&GLVertexAttrib3dv, "glVertexAttrib3dv");
    Sys_LoadGLProc((void**)&GLVertexAttrib3f, "glVertexAttrib3f");
    Sys_LoadGLProc((void**)&GLVertexAttrib3fv, "glVertexAttrib3fv");
    Sys_LoadGLProc((void**)&GLVertexAttrib3s, "glVertexAttrib3s");
    Sys_LoadGLProc((void**)&GLVertexAttrib3sv, "glVertexAttrib3sv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nbv, "glVertexAttrib4Nbv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Niv, "glVertexAttrib4Niv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nsv, "glVertexAttrib4Nsv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nub, "glVertexAttrib4Nub");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nubv, "glVertexAttrib4Nubv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nuiv, "glVertexAttrib4Nuiv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4Nusv, "glVertexAttrib4Nusv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4bv, "glVertexAttrib4bv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4d, "glVertexAttrib4d");
    Sys_LoadGLProc((void**)&GLVertexAttrib4dv, "glVertexAttrib4dv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4f, "glVertexAttrib4f");
    Sys_LoadGLProc((void**)&GLVertexAttrib4fv, "glVertexAttrib4fv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4iv, "glVertexAttrib4iv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4s, "glVertexAttrib4s");
    Sys_LoadGLProc((void**)&GLVertexAttrib4sv, "glVertexAttrib4sv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4ubv, "glVertexAttrib4ubv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4uiv, "glVertexAttrib4uiv");
    Sys_LoadGLProc((void**)&GLVertexAttrib4usv, "glVertexAttrib4usv");
    Sys_LoadGLProc((void**)&GLVertexAttribPointer, "glVertexAttribPointer");
    Sys_LoadGLProc((void**)&GLUniformMatrix2x3fv, "glUniformMatrix2x3fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix3x2fv, "glUniformMatrix3x2fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix2x4fv, "glUniformMatrix2x4fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix4x2fv, "glUniformMatrix4x2fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix3x4fv, "glUniformMatrix3x4fv");
    Sys_LoadGLProc((void**)&GLUniformMatrix4x3fv, "glUniformMatrix4x3fv");
    Sys_LoadGLProc((void**)&GLColorMaski, "glColorMaski");
    Sys_LoadGLProc((void**)&GLGetBooleani_v, "glGetBooleani_v");
    Sys_LoadGLProc((void**)&GLGetIntegeri_v, "glGetIntegeri_v");
    Sys_LoadGLProc((void**)&GLEnablei, "glEnablei");
    Sys_LoadGLProc((void**)&GLDisablei, "glDisablei");
    Sys_LoadGLProc((void**)&GLIsEnabledi, "glIsEnabledi");
    Sys_LoadGLProc((void**)&GLBeginTransformFeedback, "glBeginTransformFeedback");
    Sys_LoadGLProc((void**)&GLEndTransformFeedback, "glEndTransformFeedback");
    Sys_LoadGLProc((void**)&GLBindBufferRange, "glBindBufferRange");
    Sys_LoadGLProc((void**)&GLBindBufferBase, "glBindBufferBase");
    Sys_LoadGLProc((void**)&GLTransformFeedbackVaryings, "glTransformFeedbackVaryings");
    Sys_LoadGLProc((void**)&GLGetTransformFeedbackVarying, "glGetTransformFeedbackVarying");
    Sys_LoadGLProc((void**)&GLClampColor, "glClampColor");
    Sys_LoadGLProc((void**)&GLBeginConditionalRender, "glBeginConditionalRender");
    Sys_LoadGLProc((void**)&GLEndConditionalRender, "glEndConditionalRender");
    Sys_LoadGLProc((void**)&GLVertexAttribIPointer, "glVertexAttribIPointer");
    Sys_LoadGLProc((void**)&GLGetVertexAttribIiv, "glGetVertexAttribIiv");
    Sys_LoadGLProc((void**)&GLGetVertexAttribIuiv, "glGetVertexAttribIuiv");
    Sys_LoadGLProc((void**)&GLVertexAttribI1i, "glVertexAttribI1i");
    Sys_LoadGLProc((void**)&GLVertexAttribI2i, "glVertexAttribI2i");
    Sys_LoadGLProc((void**)&GLVertexAttribI3i, "glVertexAttribI3i");
    Sys_LoadGLProc((void**)&GLVertexAttribI4i, "glVertexAttribI4i");
    Sys_LoadGLProc((void**)&GLVertexAttribI1ui, "glVertexAttribI1ui");
    Sys_LoadGLProc((void**)&GLVertexAttribI2ui, "glVertexAttribI2ui");
    Sys_LoadGLProc((void**)&GLVertexAttribI3ui, "glVertexAttribI3ui");
    Sys_LoadGLProc((void**)&GLVertexAttribI4ui, "glVertexAttribI4ui");
    Sys_LoadGLProc((void**)&GLVertexAttribI1iv, "glVertexAttribI1iv");
    Sys_LoadGLProc((void**)&GLVertexAttribI2iv, "glVertexAttribI2iv");
    Sys_LoadGLProc((void**)&GLVertexAttribI3iv, "glVertexAttribI3iv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4iv, "glVertexAttribI4iv");
    Sys_LoadGLProc((void**)&GLVertexAttribI1uiv, "glVertexAttribI1uiv");
    Sys_LoadGLProc((void**)&GLVertexAttribI2uiv, "glVertexAttribI2uiv");
    Sys_LoadGLProc((void**)&GLVertexAttribI3uiv, "glVertexAttribI3uiv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4uiv, "glVertexAttribI4uiv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4bv, "glVertexAttribI4bv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4sv, "glVertexAttribI4sv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4ubv, "glVertexAttribI4ubv");
    Sys_LoadGLProc((void**)&GLVertexAttribI4usv, "glVertexAttribI4usv");
    Sys_LoadGLProc((void**)&GLGetUniformuiv, "glGetUniformuiv");
    Sys_LoadGLProc((void**)&GLBindFragDataLocation, "glBindFragDataLocation");
    Sys_LoadGLProc((void**)&GLGetFragDataLocation, "glGetFragDataLocation");
    Sys_LoadGLProc((void**)&GLUniform1ui, "glUniform1ui");
    Sys_LoadGLProc((void**)&GLUniform2ui, "glUniform2ui");
    Sys_LoadGLProc((void**)&GLUniform3ui, "glUniform3ui");
    Sys_LoadGLProc((void**)&GLUniform4ui, "glUniform4ui");
    Sys_LoadGLProc((void**)&GLUniform1uiv, "glUniform1uiv");
    Sys_LoadGLProc((void**)&GLUniform2uiv, "glUniform2uiv");
    Sys_LoadGLProc((void**)&GLUniform3uiv, "glUniform3uiv");
    Sys_LoadGLProc((void**)&GLUniform4uiv, "glUniform4uiv");
    Sys_LoadGLProc((void**)&GLTexParameterIiv, "glTexParameterIiv");
    Sys_LoadGLProc((void**)&GLTexParameterIuiv, "glTexParameterIuiv");
    Sys_LoadGLProc((void**)&GLGetTexParameterIiv, "glGetTexParameterIiv");
    Sys_LoadGLProc((void**)&GLGetTexParameterIuiv, "glGetTexParameterIuiv");
    Sys_LoadGLProc((void**)&GLClearBufferiv, "glClearBufferiv");
    Sys_LoadGLProc((void**)&GLClearBufferuiv, "glClearBufferuiv");
    Sys_LoadGLProc((void**)&GLClearBufferfv, "glClearBufferfv");
    Sys_LoadGLProc((void**)&GLClearBufferfi, "glClearBufferfi");
    Sys_LoadGLProc((void**)&proc GLPIENTRY , "gloc ");
    Sys_LoadGLProc((void**)&GLIsRenderbuffer, "glIsRenderbuffer");
    Sys_LoadGLProc((void**)&GLBindRenderbuffer, "glBindRenderbuffer");
    Sys_LoadGLProc((void**)&GLDeleteRenderbuffers, "glDeleteRenderbuffers");
    Sys_LoadGLProc((void**)&GLGenRenderbuffers, "glGenRenderbuffers");
    Sys_LoadGLProc((void**)&GLRenderbufferStorage, "glRenderbufferStorage");
    Sys_LoadGLProc((void**)&GLGetRenderbufferParameteriv, "glGetRenderbufferParameteriv");
    Sys_LoadGLProc((void**)&GLIsFramebuffer, "glIsFramebuffer");
    Sys_LoadGLProc((void**)&GLBindFramebuffer, "glBindFramebuffer");
    Sys_LoadGLProc((void**)&GLDeleteFramebuffers, "glDeleteFramebuffers");
    Sys_LoadGLProc((void**)&GLGenFramebuffers, "glGenFramebuffers");
    Sys_LoadGLProc((void**)&GLCheckFramebufferStatus, "glCheckFramebufferStatus");
    Sys_LoadGLProc((void**)&GLFramebufferTexture1D, "glFramebufferTexture1D");
    Sys_LoadGLProc((void**)&GLFramebufferTexture2D, "glFramebufferTexture2D");
    Sys_LoadGLProc((void**)&GLFramebufferTexture3D, "glFramebufferTexture3D");
    Sys_LoadGLProc((void**)&GLFramebufferRenderbuffer, "glFramebufferRenderbuffer");
    Sys_LoadGLProc((void**)&GLGetFramebufferAttachmentParameteriv, "glGetFramebufferAttachmentParameteriv");
    Sys_LoadGLProc((void**)&GLGenerateMipmap, "glGenerateMipmap");
    Sys_LoadGLProc((void**)&GLBlitFramebuffer, "glBlitFramebuffer");
    Sys_LoadGLProc((void**)&GLRenderbufferStorageMultisample, "glRenderbufferStorageMultisample");
    Sys_LoadGLProc((void**)&GLFramebufferTextureLayer, "glFramebufferTextureLayer");
    Sys_LoadGLProc((void**)&GLMapBufferRange, "glMapBufferRange");
    Sys_LoadGLProc((void**)&GLFlushMappedBufferRange, "glFlushMappedBufferRange");
    Sys_LoadGLProc((void**)&GLBindVertexArray, "glBindVertexArray");
    Sys_LoadGLProc((void**)&GLDeleteVertexArrays, "glDeleteVertexArrays");
    Sys_LoadGLProc((void**)&GLGenVertexArrays, "glGenVertexArrays");
    Sys_LoadGLProc((void**)&GLIsVertexArray, "glIsVertexArray");
}
